default: &default
  site:
    name: 陌邻
    host: http://api-dev.imolin.cn/
    copyright: © imolin All Right Reserved 2017
    description: 陌邻是一个小区生活互助交流大数据平台，陌邻APP提供小区邻友社交互动，提供全方位社区便民服务，通过人工智能，让周边服务，呼之即来。
    slogan: 陌邻，让邻里不再陌生！
  email:
    sender: sender@tmf.com
  weixin:
    app_id: wx2112a27b1c8bb766
    app_secret: d4624c36b6795d1d99dcf0547af5443d
    token_string: 50c2263e7f076bbe75c50ebd54401963 # 微信Token值
    secret_string: 0abcf2c591b0a1b209ca12a20a8eda83 # 微信服务URL配置中，此值用来避免真正使用的Token值暴露在URL上，提高安全性。
    encoding_aes_key:
  weixin_open_app: # 微信开放平台绑定的APP
    app_id: wxac397d203f8b9e59
    app_secret: 4e2df100543ca82058edf65a480d5d8f
  sms:
    provider: yun_pian_v1
    yun_pian_v1:
      api_key: c97380fa188341572c1bcdadf383dfc2
  mobile:
    auth_token_template: "【陌邻社区】您的验证码是#code#。如非本人操作，请忽略本短信。"
    test_mobile:
      phone: '13900000000'
      code: '000000'

  payment: # Ping++支付
    api_id:
    api_key:
    channels:
    - alipay_wap
    - wx_pub
    enable_pingpp_one: false

  qiniu: &qiniu_credentials
    access_key: HXrvQOeDfAizpMzdanxSMiotX60zWuDXAseybFcx
    secret_key: n886ogK5IGUwYx-M4m-NLSaP0-OTGD2_eCCsqId_

  paperclip:
    enable: true
    options:
      storage: :qiniu
      qiniu_credentials:
        <<: *qiniu_credentials
      bucket: tmf
      use_timestamp: false
      qiniu_host: ocwr8qu9g.bkt.clouddn.com

development:
  <<: *default
production:
  <<: *default
test:
  <<: *default
