default: &default
  site:
    name: 淘美客
    host: http://localhost:5000
    copyright: © MoKoMo All Right Reserved 2015
    description: 淘美客是一家提供在线美容预约服务的互联网平台，专业打造优质舒适的社区美容服务，拥有丰富多样的美容项目、各有所长的美容技师供您自由选择。
    slogan: 定制私人美容，想约就约放心选择
  email:
    sender: sender@tmf.com
  weixin:
    app_id: wx2112a27b1c8bb766
    app_secret: d4624c36b6795d1d99dcf0547af5443d
    token_string: 50c2263e7f076bbe75c50ebd54401963 # 微信Token值
    secret_string: 0abcf2c591b0a1b209ca12a20a8eda83 # 微信服务URL配置中，此值用来避免真正使用的Token值暴露在URL上，提高安全性。
    encoding_aes_key:
  weixin_open_app: # 微信开放平台绑定的APP
    app_id:
    app_secret:
  sms:
    provider: yun_pian_v1
    yun_pian_v1:
      api_key: c97380fa188341572c1bcdadf383dfc2
  mobile:
    auth_token_template: "【淘美客】您的验证码是#code#。如非本人操作，请忽略本短信。"

  payment: # Ping++支付
    api_id:
    api_key:
    channels:
    - alipay
    - wx
    enable_pingpp_one: false

  qiniu: &qiniu_credentials
    access_key: HXrvQOeDfAizpMzdanxSMiotX60zWuDXAseybFcx
    secret_key: n886ogK5IGUwYx-M4m-NLSaP0-OTGD2_eCCsqId_

  paperclip:
    enable: true
    options:
      storage: :qiniu
      qiniu_credentials:
        <<: *qiniu_credentials
      bucket: tmf
      use_timestamp: false
      qiniu_host: ocwr8qu9g.bkt.clouddn.com

development:
  <<: *default
production:
  <<: *default
test:
  <<: *default
