default: &default
  site:
    name: tmf
    host: localhost
    copyright: © TMF All Right Reserved 2015
    description: 私享荟一个网络购物平台
  email:
    sender: sender@tmf.com
development:
  <<: *default
production:
  <<: *default
test:
  <<: *default
